#!/bin/bash

# Указать путь к целевой папке
target_directory="/home/gerben/fuzzer/race_condition/corpus"

# Перейти в целевую папку
cd "$target_directory" || exit

# Перебираем файлы в целевой папке
for file in *; do
    # Проверяем, начинается ли имя файла с "1" или "2"
    if [[ "$file" == [12]* ]]; then
        # Оставляем файлы, начинающиеся с "1" или "2" нетронутыми
        continue
    else
        # Удаляем остальные файлы
        rm -f "$file"
        echo "Удалено: $file"
    fi
done

